### ISSUE TITLE
Trouble running authentication-db.sql 

### ISSUE THREAD

**Issue by madrinathapa** [airavata-courses/saurabh#1]
Please refer the image for the details. 
![screen shot 2017-08-31 at 2 09 44 am](https://user-images.githubusercontent.com/5130996/29908980-d8b3e048-8df1-11e7-8854-10e5017c2494.png)

**Comment by saurabhagrawal0412** [comment]
Hi,
Thanks for finding this issue.
I got the same error once, but when I checked, the user was created.
Unfortunately, this issue no longer reproduces on my system.
Can you please check if (despite this error) the user is created or not?
You can execute this query on your **MySQL Workbench** for the same:
`SELECT User FROM mysql.user where user='authentication_user';`

Thanks

**Comment by singhPrasan** [comment]
@saurabhagrawal0412 I get the same error while executing the script. But when I run the query you provided, it returns authentication_user. So, it seems like the script is running despite the attached error

**Comment by saurabhagrawal0412** [comment]
Hi @madrinathapa and @SinghPrasandeep ,
Thanks for pointing out this issue.
There was a bug in the script.
The queries were in an incorrect order,
also, there was a drop statement (which I put during testing).
Please try to execute the script now.

Thanks

**Comment by singhPrasan** [comment]
@saurabhagrawal0412 Did a fresh pull after your commit. The error persists.

**Comment by saurabhagrawal0412** [comment]
@SinghPrasandeep ,
It might be because the user and db are already created.
Can you try executing the **following queries** before executing the DB script?
```
drop user `authentication_user`@`localhost`;
drop database `authentication-db`;
```

**Comment by saurabhagrawal0412** [comment]
Hi @SinghPrasandeep ,
All the scripts should be working now.
Previously, the scripts were not working because the users and databases (for resource-db and authorization-db) were already created, and these scripts try to create those again.
Now, I have changed the scripts so that they don't try to create database objects if they already exist.

**Comment by saurabhagrawal0412** [comment]
Hi @madrinathapa ,
Regarding the permissions error,
It seems like the script does not have `EXECUTE` permission.
You can change the permission of the script by running the command:
``sudo chmod 777 authentication_Service.py``
from the [home directory](https://github.com/airavata-courses/saurabhagrawal0412/tree/master/authentication-service) of this service.

**Comment by singhPrasan** [comment]
@saurabhagrawal0412 All scripts are working on my system now.

**Comment by madrinathapa** [comment]
@saurabhagrawal0412 Yes, same here.
