### ISSUE TITLE
Branching and Wiki

### ISSUE THREAD

**Issue by marpierc** [airavata-courses/saurabh#2]
Please create a separate branch for each assignment. Alternatively, you can use a subdirectory for each assignment.  Please also use the GitHub wiki for assignment documentation. Minimally the wiki should describe installation and testing.

**Comment by saurabhagrawal0412** [comment]
Hi Prof @marpierc ,
Created the [Wiki](https://github.com/airavata-courses/saurabhagrawal0412/wiki).

**Comment by saurabhagrawal0412** [comment]
Hi Prof @marpierc ,
Created the [Wiki](https://github.com/airavata-courses/saurabhagrawal0412/wiki).
Additionally, have moved the current code into the directory **Assignment1**
