### ISSUE TITLE
Permission error

### ISSUE THREAD

**Issue by saurabhagrawal0412** [airavata-courses/saurabh#4]
Hi @madrinathapa ,
Regarding the permissions error,
it seems like the script does not have EXECUTE permission on your system.
You can change the permission of the script by running the command:
``sudo chmod 777 authentication_Service.py``
from the home directory of this service.
Please let me know if it works.

Thanks.

**Comment by madrinathapa** [comment]
Hi @saurabhagrawal0412 ,

This issue was because of the incorrect sql script that I executed initially. Everything is working fine now. 

Thank you,
Madrina Thapa
