### ISSUE TITLE
Missing API Server

### ISSUE THREAD

**Issue by eldhomathulla** [airavata-courses/saurabh#5]
Please implement an API server, which serve as a entry point for calling microservices.
<img width="1334" alt="30230833-027f2ee4-94b6-11e7-8aa9-a1b55215c390" src="https://user-images.githubusercontent.com/8665601/30253500-9c8a76d4-9654-11e7-899d-62a19715b097.png">

**Comment by saurabhagrawal0412** [comment]
@eldhomathulla ,
Have added the API server.
Will update the documentation soon.
