### ISSUE TITLE
Service terminates after processing one request

### ISSUE THREAD

**Issue by saurabhagrawal0412** [airavata-courses/saurabh#7]
Hi @eldhomathulla , @Ameya05 , @tilaks26 
I have a [service](https://github.com/airavata-courses/saurabh/blob/master/Assignment2/authorization_service/index.js) that acts both as RPC server and client.
That is
1) It listens for RPC requests
2) Once it gets a request, it makes an RPC request to the [next service](https://github.com/airavata-courses/saurabh/tree/master/Assignment2/resource_service_messaging)

This whole model works for one request, but after it sends the response to the first request, the service terminates.
Please suggest something.

**Comment by tilaks26** [comment]
Can you add loggers and check where the flow is terminating?

**Comment by saurabhagrawal0412** [comment]
**Resolved**
There was a statement that terminated the process. Working fine after removing that statement.
