### ISSUE TITLE
Assignment 2 Comments

### ISSUE THREAD

**Issue by tilaks26** [airavata-courses/saurabh#9]
I have a few suggestions/comments -

- You need to mention the steps with which I can build and run your submission (not just links where I can test it)
- Include a Jenkins file to build and deploy your application on Jetstream.
- Have a provision to trigger build (with or without the Github hook)

Can you please make these changes and link this issue with the commit so I can review it?

**Comment by saurabhagrawal0412** [comment]
Hi @tilaks26 ,

Please find the steps to run the app locally [here](https://github.com/airavata-courses/saurabh/wiki/Assignment-2#how-to-set-this-up-on-your-system)

Will be done with the Jenkins file in 3-4 hours

**Comment by saurabhagrawal0412** [comment]
@tilaks26 ,
I have created a [Jenkins job](http://149.165.168.193:8080/job/main_job/) that is triggered by Github. It builds the project on the same machine and deploys it on another instance via SSH.
Credentials: `admin/password`
Do I still need to create a Jenkinsfile?

**Comment by tilaks26** [comment]
Thank you. This is sufficient.
